algoritmo "exemploSE"
var
   nome:caractere
   salario:real
inicio
   escreva("Digite seu nome:")
   leia(nome)
   escreva("Digite seu salario:")
   leia(salario)
   se(salario>1200)entao
      escrevaL(nome, " seu salario é maior que o salario minimo")
   senao
      se(salario=1200)entao
         escreval(nome, " seu salario é igual salario minimo")
      senao
         escreval(nome, " seu salario é menor que o salario minimo"))
      fimse
   fimse fimse
fimalgoritmo