algoritmo "ImprimeFor1a10"
var
   j:inteiro
inicio
   // imprimindo de 1 a 10
   //escreval("Imprimindo de 1 a 10:")
   //para j de 1 ate 10 faca
     // escreval(j)
   //fimpara
   
   // imprimindo de 10 a 1
   //escreval("Imprimindo de 10 a 1:")
   //para j de 10 ate 1 passo j-1 faca
      //escreval(j)
   //fimpara
   
   // imprimindo de 10 a 1 de 2 em 2
   escreval("Imprimindo de 10 a 1:")
   para j de 10 ate 1 passo j-2 faca
      escreval(j)
   fimpara

fimalgoritmo